### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kvachkov** [ondrejsika/zcashd-miner#1]
Hi, 
C:\Python27\Scripts\.env\Scripts>python zcashd-miner.py -a t1MeH2fDxnzHWvnysSs2rVoWiv6P1nDBDK5 eu1-zcash.flypool.org:3333 1
Traceback (most recent call last):
  File "zcashd-miner.py", line 17, in <module>
    miner = ZcashdMiner(args.zcashd_url)
  File "C:\Python27\Scripts\.env\Scripts\libzcashdminer\miner.py", line 17, in __init__
    self.solver = Solver()
  File "C:\Python27\Scripts\.env\Scripts\libzcashdminer\pyzceqsolver\solver.py", line 62, in __init__
    self._ensure_library()
  File "C:\Python27\Scripts\.env\Scripts\libzcashdminer\pyzceqsolver\solver.py", line 80, in _ensure_library
    load_library()
  File "C:\Python27\Scripts\.env\Scripts\libzcashdminer\pyzceqsolver\solver.py", line 54, in load_library
    library = ffi.dlopen(library_pathname)
  File "C:\Python27\Scripts\.env\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Python27\Scripts\.env\lib\site-packages\cffi\api.py", line 795, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Python27\Scripts\.env\lib\site-packages\cffi\api.py", line 790, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library C:\Python27\Scripts\.env\Scripts\libzcashdminer\pyzceqsolver\zceqsolver.dll: error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Python27\\Scripts\\.env\\Scripts\\libzcashdminer\\pyzceqsolver\\zceqsolver.dll'
Exception AttributeError: "'NoneType' object has no attribute 'DestroySolver'" in <bound method Solver.__del__ of <libzcashdminer.pyzceqsolver.solver.Solver instance at 0x02C3F580>> ignored

What is the problem?

**Comment by ondrejsika** [comment]
There is just Linux binary of solver library.

This is not a stratum miner, you cant mine against pool. This is miner for development purpose, mainly designed for mining regtest chain (with zero difficulty) against zcashd (not a pool). There is not `-a` param (https://github.com/ondrejsika/zcashd-miner#usage). Check out this miner -
 https://minergate.com/altminers/nheqminer
